- name: ensure ssh directory exists
  file:
    path: /home/{{ dork_user }}/.ssh
    state: directory

- name: write authorized keys file
  template:
    src: authorized_keys.j2
    dest: /home/{{ dork_user }}/.ssh/authorized_keys

- name: create source and build directories
  file:
    path: /var/{{ item }}
    state: directory
    owner: "{{ dork_user }}"
  with_items:
  - source
  - build

- name: create ansible directory
  file:
    path: /etc/ansible
    state: directory

- name: create ansible hosts file
  template:
    src: hosts.j2
    dest: /etc/ansible/hosts

- name: copy roles.yml
  copy:
    src: /vagrant/roles.yml
    dest: /etc/ansible/roles.yml
  when: not dork_custom is defined

- name: copy roles.yml
  copy:
    src: /opt/roles/{{ dork_custom }}/vagrant/roles.yml
    dest: /etc/ansible/roles.yml
  when: dork_custom is defined

- name: run ansible-galaxy install
  shell: ansible-galaxy install --no-deps --force --role-file=/etc/ansible/roles.yml

- name: create custom roles and playbooks directories
  file:
    path: /opt/{{ item }}
    state: directory
  with_items:
  - playbooks
  - roles

- name: sync custom roles and playbooks
  synchronize:
    src: /opt/{{ item }}/
    dest: /opt/{{ item }}/
    recursive: yes
  with_items:
  - playbooks
  - roles
  when: not dork_custom is defined

- name: sync custom roles and playbooks
  synchronize:
    src: /opt/roles/custom/{{ dork_custom }}/{{ item }}/
    dest: /opt/{{ item }}/
    recursive: yes
  with_items:
  - playbooks
  - roles
  when: dork_custom is defined

