# Basic directories
- name: create group dork
  group:
    name: dork
    state: present

- name: create source and build directories
  file:
    path: /var/{{ item }}
    state: directory
    group: dork
    mode: 0775
  with_items:
  - source
  - build
  - data

- name: create ansible directory
  file:
    path: /etc/ansible
    state: directory

- name: create ansible hosts file
  template:
    src: hosts.j2
    dest: /etc/ansible/hosts.d/self

# ======================================================================
# Clone dorkstation
# ======================================================================
- name: clone dorkstation
  git:
    repo: "{{ server_dorkstation_repo }}"
    accept_hostkey: yes
    dest: /opt/dorkstation
  tags:
  - update-dork

# ======================================================================
# roles.yml containing roles to download
# ======================================================================
- name: copy roles.yml
  file:
    src: /opt/dorkstation/vagrant/roles.yml
    dest: /etc/ansible/roles.yml
    state: link

- name: run ansible-galaxy install
  shell: ansible-galaxy install --no-deps --force --role-file=/etc/ansible/roles.yml
  tags:
  - update-dork

# ======================================================================
# Custom roles and playbooks
# ======================================================================
- name: sync custom roles and playbooks
  file:
    src: /opt/dorkstation/{{ item }}
    dest: /opt/{{ item }}
    state: link
  with_items:
  - playbooks
  - roles
