# Basic directories
- name: create source and build directories
  file:
    path: /var/{{ item }}
    state: directory
    group: dork
    mode: 0775
  with_items:
  - source
  - build

- name: create ansible directory
  file:
    path: /etc/ansible
    state: directory

- name: create ansible hosts file
  template:
    src: hosts.j2
    dest: /etc/ansible/hosts.d/self.ini

# ======================================================================
# Clone dorkstation
# ======================================================================
- name: clone dorkstation
  git:
    repo: "{{ server_dorkstation_repo }}"
    accept_hostkey: yes
    dest: /opt/dorkstation

# ======================================================================
# roles.yml containing roles to download
# ======================================================================
- name: copy roles.yml
  file:
    src: /opt/dorkstation/vagrant/roles.yml
    dest: /etc/ansible/roles.yml
    state: link

- name: run ansible-galaxy install
  shell: ansible-galaxy install --no-deps --force --role-file=/etc/ansible/roles.yml

# ======================================================================
# Custom roles and playbooks
# ======================================================================
- name: sync custom roles and playbooks
  file:
    src: /opt/dorkstation/{{ item }}
    dest: /opt/{{ item }}
    state: link
  with_items:
  - playbooks
  - roles

# ======================================================================
# Custom inventory
# ======================================================================
- name: sync custom roles and playbooks
  copy:
    src: /opt/roles/custom/{{ dork_custom}}/vagrant/inventory.ini
    dest: /etc/ansible/hosts.d/custom.ini
  when: dork_custom is defined

- name: sync custom roles and playbooks
  copy:
    src: /vagrant/inventory.ini
    dest: /etc/ansible/hosts.d/custom.ini
  when: not dork_custom is defined
